### ISSUE TITLE
reader: Handoff embed allowlist is hardcoded to handoff.j5s.dev — derive it from the reader's own host

### ISSUE THREAD

**Issue by toshimoto821** [bffless/apps#498]
Found subscribing Rivulet at `reader.bffless.dev` to `https://handoff.bffless.dev/feed/reader/ai-engineering.xml`: `post.md` lists, but the reading pane shows only `post.md (16.8 KB)`. **decided**: replace the hardcoded origin list with a same-site rule derived from the reader's own hostname — any `https` origin whose host is a subdomain of the reader's primary domain (the hostname minus its first label, the same split `adminOrigin()` does) is trusted — so Handoff as `handoff.`, `h2.` or any label works, and a reader at `r2.` derives the same primary domain; a `VITE_TRUSTED_EMBED_ORIGINS` env var replaces the rule with an exact-origin list when Handoff is on a different domain. The `https://handoff.j5s.dev` literal goes away (it satisfies the rule on the j5s.dev instance). Citations against `origin/main` `e1b706a`.

## What happens

The feed is correct: Handoff emits a `text/markdown` `<enclosure>` plus a name + size `<description>` (`apps/handoff/src/lib/feed.ts:203`, `apps/handoff/src/lib/feed.ts:215`), which the reader ingests (`apps/reader/.bffless/proxy-rules/reader/rules/api/refresh/post/rule.yaml:51`); the viewer's CSP already allows `frame-ancestors https://*.bffless.dev`.

What fails is the trust gate. `TRUSTED_EMBED_ORIGINS` is a compile-time constant holding one origin, `https://handoff.j5s.dev` (`apps/reader/src/lib/embed.ts:23`); `isEmbeddable` requires the `link` origin to be in it (`apps/reader/src/lib/embed.ts:88`), so a `handoff.bffless.dev` link is `false`, `ReadingPane` skips the iframe (`apps/reader/src/components/ReadingPane.tsx:66`, `apps/reader/src/components/ReadingPane.tsx:162`) and renders the sanitized `content ?? summary` (`apps/reader/src/lib/items.ts:102`, `apps/reader/src/components/ReadingPane.tsx:58`) — the `<description>`.

Every install but j5s.dev hits this. The manifests default to subdomains `handoff` (`apps/handoff/bffless-app.json:31`) and `reader` (`apps/reader/bffless-app.json:27`) but an installer can pick other labels; what is fixed is that both sit on one primary domain — the topology the embed design assumes (`apps/reader/docs/superpowers/specs/2026-07-08-reader-embed-content-design.md:37`).

## Expected

A Handoff feed on the reader's primary domain embeds `text/markdown` and `text/html` items inline (behind the existing per-origin consent gate) on any install, whatever subdomains the apps use, with no code edit.

## Suggested fix

Mirror `adminOrigin()` (`apps/reader/src/lib/session.ts:248`) — it splits off the first hostname label so "a fork works on any instance with no code edit", `VITE_ADMIN_URL` overriding (`apps/reader/src/lib/session.ts:249`).

1. Replace the `TRUSTED_EMBED_ORIGINS` constant (`apps/reader/src/lib/embed.ts:23`) with an `isTrustedEmbedOrigin(origin: string): boolean` predicate: if `import.meta.env.VITE_TRUSTED_EMBED_ORIGINS` is set, true only for an exact match against its comma-separated entries (trimmed, trailing slashes stripped) — an override replaces the rule, like `VITE_ADMIN_URL`; otherwise take `primary = window.location.hostname` minus its first label and return true iff the protocol is `https:` and the hostname ends with `.${primary}` (apex not trusted; `http:` never). A single-label host (localhost) has no primary domain, so nothing embeds unless the env var is set.
2. `isEmbeddable`'s second parameter (`apps/reader/src/lib/embed.ts:82`) becomes an injectable predicate defaulting to `isTrustedEmbedOrigin`, replacing the list `includes` at `apps/reader/src/lib/embed.ts:88`. `EMBEDDABLE_MIMES` (`apps/reader/src/lib/embed.ts:35`) and the per-origin consent layer are unchanged. Update the "small hardcoded constant on purpose" doc comment and the list-injecting case at `apps/reader/src/lib/embed.test.ts:90`.
3. Tests: the `isEmbeddable` cases in `apps/reader/src/lib/embed.test.ts:42` run under `// @vitest-environment-options {"url":"https://reader.example.com/"}` (jsdom refuses to redefine `window.location`) with `vi.stubEnv` + `afterEach` unstub (`apps/reader/src/lib/session.test.ts:9`), and assert: `https://handoff.example.com/blob/x.md` and `https://h2.example.com/blob/x.md` embed; `https://handoff.j5s.dev/blob/x.md`, `http://handoff.example.com/...`, `https://example.com/...` (apex) and `https://notexample.com/...` do not; with `VITE_TRUSTED_EMBED_ORIGINS=https://docs.custom.tld/, https://other.tld` only those two origins embed (`https://handoff.example.com` then does not); on `localhost` nothing embeds. Move the `handoff.j5s.dev` fixtures in `apps/reader/src/components/ReadingPane.test.tsx` (lines 42, 51, 100, 109, 123) to that host under the same docblock, and document `VITE_TRUSTED_EMBED_ORIGINS` beside `VITE_ADMIN_URL` in `apps/reader/bffless/README.md:185`.

- [ ] A `text/markdown` or `text/html` item whose `link` is `https://<any-label>.<reader's primary domain>/...` is embeddable on any install; `https://handoff.j5s.dev` is no longer special-cased anywhere in `apps/reader/src`.
- [ ] `VITE_TRUSTED_EMBED_ORIGINS` (comma-separated origins, exact match) replaces the same-site rule when set; unset on a single-label host embeds nothing.
- [ ] Test: the step 3 cases in `apps/reader/src/lib/embed.test.ts`, plus the `ReadingPane.test.tsx` fixtures moved off the j5s.dev literal.

Verify: `pnpm reader:lint && pnpm reader:build && pnpm reader:test`.

## Notes

- No rule or schema change. Live check on the PR preview (`preview-reader.yml`, runs on PR open): subscribe it to the feed above, open `post.md`.
- Introduced by #205 and #209; #206's enclosure backfill makes existing items pick this up on the next refresh.
- Enterprise topology (document in the README paragraph; no extra code): apps live at `<app>.<workspace>.workspace.<primaryDomain>`, so "hostname minus first label" is `<workspace>.workspace.<primaryDomain>` and the rule trusts that workspace's own Handoff while excluding sibling workspaces (a different suffix).
- Not in scope: the Handoff side — `feed.ts` line 215 is what #201 chose. Unrelated to #146.
